# Generated by Django 4.2.5 on 2023-09-17 09:46

from django.db import migrations

SPECIALIZATIONS = [
    "Mentor",
    "Intern",
    "Project Manager",
]


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    def insertData(apps, schema_editor):
        SpecializationModel = apps.get_model('members', 'Specialization')
        for x in SPECIALIZATIONS:
            specialization = SpecializationModel(name=x)
            specialization.save()

    operations = [
        migrations.RunPython(insertData),
    ]
