# Generated by Django 4.2.5 on 2023-09-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20230917_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date',
            field=models.ManyToManyField(related_name='activity', to='members.date'),
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='members'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='specialization',
        ),
        migrations.AddField(
            model_name='member',
            name='specialization',
            field=models.ManyToManyField(to='members.specialization'),
        ),
    ]
