# Generated by Django 4.2.5 on 2023-09-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_date_member_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.ManyToManyField(blank=True, related_name='activity', to='members.date'),
        ),
    ]
