# Generated by Django 4.2.5 on 2023-10-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial_squashed_0004_alter_member_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
