# Generated by Django 4.2.5 on 2023-10-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_created_at_member_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='dates',
            new_name='activities',
        ),
    ]
